# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# configuration of the Model Control Plane
model:
  name: credit_scoring_model
  version: gb
  license: Apache 2.0
  description: A credit scoring model
  tags: ["credit_scoring", "classifier"]

# Configure the pipeline
parameters:
  model_type: "gb" # GradientBoosting
  protected_attributes:
    - "gender"
    - "age_group"
