model:
  name: gpt2
  description: "Deploy `openai-community/gpt2` using vllm."
  tags:
    - llm
    - vllm
    - openai-community/gpt2

steps:
  vllm_model_deployer_step:
    parameters:
      config:
        model: openai-community/gpt2
