# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# Pipeline options
enable_cache: False
enable_artifact_metadata: True
