# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
      - s3
      - aws
      - slack
    requirements: requirements.txt
    python_package_installer: "uv"

# Pipeline options
enable_cache: False
enable_artifact_metadata: True

steps:
  modal_deployment:
    settings:
      resources:
        cpu_count: 6
        memory: "14GB"
