# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# Pipeline options
enable_cache: False
enable_artifact_metadata: True

# Pipeline configuration
parameters:
  test_size: 0.35
  sample_fraction: null
