# environment configuration
settings:
  docker:
    required_integrations:
      - sklearn
      - pandas
    requirements:
      - pyarrow

# Pipeline options
enable_cache: True
enable_artifact_metadata: True

# Pipeline parameters
parameters:
  protected_attributes:
    - "scale__CODE_GENDER"
    - "scale__DAYS_BIRTH"
    - "scale__NAME_EDUCATION_TYPE"
    - "scale__NAME_FAMILY_STATUS"
    - "scale__NAME_HOUSING_TYPE"
