# OCR Comparison Pipeline Configuration

# Image input configuration
# image_paths and image_folder are combined if both are provided
input:
  image_paths: ["assets/street_signs/montreal.jpg"] # List of specific image paths to process
  image_folder: null # Folder containing images to process

models:
  custom_prompt: null # Optional custom prompt
  model1: null # First model for comparison
  model2: null # Second model for comparison
  models: # List of models to compare (takes precedence over model1 and model2)
    - mistral/pixtral-12b-2409
    - llama3.2-vision:11b
    - gemma3:27b
  ground_truth_model: "gpt-4o-mini" # Model to use for ground truth when source is "openai"

ground_truth:
  source: "openai" # Source for ground truth: "openai", "manual", "file", or "none"
  texts: [] # Ground truth texts (for manual source)
  file: null # Path to ground truth JSON file (for file source)

output:
  # OCR Results
  ocr_results:
    save: true
    directory: "ocr_results" # Base directory for OCR results

  # Ground truth data
  ground_truth:
    save: true
    directory: "ocr_results" # Base directory for ground truth

  # Visualization
  visualization:
    save: true
    directory: "visualizations"
