model:
  name: mistral-7b-lora
  description: "Fine-tune `mistralai/Mistral-7B-Instruct-v0.1`."
  tags:
    - llm
    - lora
    - mistral

steps:
  evaluate:
    parameters:
      config:
        model_repo: mistralai/Mistral-7B-Instruct-v0.1
        adapter_repo: ...
        precision: bf16-true