# FloraCast Training Configuration
# This config is used for local development and training

settings:
  docker:
    requirements: requirements.txt
    python_package_installer: uv

model:
  name: floracast_tft
  license: apache
  description: "TFT model for DFG time series forecasting use case"
  audience: "DFG forecasting team"
  use_cases: >
    Demonstrates ZenML MLOps capabilities for time series forecasting using 
    Temporal Fusion Transformer with custom Darts materializers and proper 
    artifact management for production forecasting workflows.
  ethics: "No ethical concerns - synthetic ecommerce data for demonstration"
  tags:
    - forecasting
    - tft
    - darts
    - time-series
    - production
    - dfg

steps:
  ingest_data:
    parameters:
      data_source: "ecommerce_default"
      data_path: null
      datetime_col: "ds"
      target_col: "y"
  
  preprocess_for_training:
    parameters:
      datetime_col: "ds"
      target_col: "y"
      freq: "D"
      val_ratio: 0.2
  
  train_model:
    parameters:
      model_name: "TFTModel"
      input_chunk_length: 30
      output_chunk_length: 7
      hidden_size: 32
      lstm_layers: 1
      num_attention_heads: 2
      dropout: 0.1
      batch_size: 16
      n_epochs: 3
      random_state: 42
      add_relative_index: true
      enable_progress_bar: false
      enable_model_summary: false
  
  evaluate:
    parameters:
      horizon: 7
      metric: "smape"
