# environment configuration
settings:
  docker:
    requirements:
      - ratelimit
      - pgvector
      - psycopg2-binary
      - beautifulsoup4
      - unstructured
      - pandas
      - numpy
      - sentence-transformers>=3
      - transformers==4.43.1
      - litellm
      - ollama
      - tiktoken
      - umap-learn
      - matplotlib
      - pyarrow
      - rerankers[flashrank]
      - datasets
      - torch
      - distilabel
      - argilla
      - pygithub
    environment:
      ZENML_PROJECT_SECRET_NAME: llm_complete


# configuration of the Model Control Plane
model:
  name: prod_finetuned-zenml-docs-embeddings
  version: latest
  license: Apache 2.0
  description: Finetuned LLM on ZenML docs
  tags: ["rag", "finetuned"]
