enable_cache: False

# environment configuration
settings:
  docker:
    requirements:
      - unstructured
      - sentence-transformers>=3
      - pgvector
      - datasets
      - litellm
      - numpy
      - psycopg2-binary
      - tiktoken
      - ratelimit
      - rerankers
      - pygithub
    environment:
      ZENML_PROJECT_SECRET_NAME: llm_complete
      ZENML_ENABLE_RICH_TRACEBACK: FALSE
      ZENML_LOGGING_VERBOSITY: INFO


# configuration of the Model Control Plane
model:
  name: staging_finetuned-zenml-docs-embeddings
  license: Apache 2.0
  description: A fine-tuned embeddings model for ZenML documentation. Used for RAG retrieval.
  tags: ["rag", "finetuned"]
  limitations: Only works for ZenML documentation. Not generalizable to other domains. Entirely build with synthetic data. The data is also quite noisy on account of how the chunks were split.
  trade_offs: Focused on a specific RAG retrieval use case. Not generalizable to other domains.
  audience: ZenML users
  use_cases: RAG retrieval

steps:
  url_scraper:
    parameters:
      docs_url: https://docs.zenml.io
      use_dev_set: false
    enable_cache: true
    step_operator: "gcp_a100"